
server:
  port: 8080
spring:
  application:
    name: SpringBootDemo
#    ???
#  devtools:
#    restart:
#      enabled:true
#    additional-paths:
#      src/main/java

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringBoot
    username: root
    password: root

